// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(lokii_coreFFI)
import lokii_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_lokii_core_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_lokii_core_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureLokiiCoreInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterDouble: FfiConverterPrimitive {
    typealias FfiType = Double
    typealias SwiftType = Double

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Double {
        return try lift(readDouble(&buf))
    }

    public static func write(_ value: Double, into buf: inout [UInt8]) {
        writeDouble(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Callback interface for Rust → Swift event notifications.
 */
public protocol EventHandler: AnyObject, Sendable {
    
    func onIndexProgress(phase: String, scannedFiles: UInt64) 
    
    func onIndexReady(total: UInt64) 
    
    func onIndexUpdated(newTotal: UInt64) 
    
    func onWatcherError(msg: String) 
    
    func onConfigReloaded() 
    
}
/**
 * Callback interface for Rust → Swift event notifications.
 */
open class EventHandlerImpl: EventHandler, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_lokii_core_fn_clone_eventhandler(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_lokii_core_fn_free_eventhandler(pointer, $0) }
    }

    

    
open func onIndexProgress(phase: String, scannedFiles: UInt64)  {try! rustCall() {
    uniffi_lokii_core_fn_method_eventhandler_on_index_progress(self.uniffiClonePointer(),
        FfiConverterString.lower(phase),
        FfiConverterUInt64.lower(scannedFiles),$0
    )
}
}
    
open func onIndexReady(total: UInt64)  {try! rustCall() {
    uniffi_lokii_core_fn_method_eventhandler_on_index_ready(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(total),$0
    )
}
}
    
open func onIndexUpdated(newTotal: UInt64)  {try! rustCall() {
    uniffi_lokii_core_fn_method_eventhandler_on_index_updated(self.uniffiClonePointer(),
        FfiConverterUInt64.lower(newTotal),$0
    )
}
}
    
open func onWatcherError(msg: String)  {try! rustCall() {
    uniffi_lokii_core_fn_method_eventhandler_on_watcher_error(self.uniffiClonePointer(),
        FfiConverterString.lower(msg),$0
    )
}
}
    
open func onConfigReloaded()  {try! rustCall() {
    uniffi_lokii_core_fn_method_eventhandler_on_config_reloaded(self.uniffiClonePointer(),$0
    )
}
}
    

}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceEventHandler {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceEventHandler] = [UniffiVTableCallbackInterfaceEventHandler(
        onIndexProgress: { (
            uniffiHandle: UInt64,
            phase: RustBuffer,
            scannedFiles: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onIndexProgress(
                     phase: try FfiConverterString.lift(phase),
                     scannedFiles: try FfiConverterUInt64.lift(scannedFiles)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onIndexReady: { (
            uniffiHandle: UInt64,
            total: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onIndexReady(
                     total: try FfiConverterUInt64.lift(total)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onIndexUpdated: { (
            uniffiHandle: UInt64,
            newTotal: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onIndexUpdated(
                     newTotal: try FfiConverterUInt64.lift(newTotal)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onWatcherError: { (
            uniffiHandle: UInt64,
            msg: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onWatcherError(
                     msg: try FfiConverterString.lift(msg)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onConfigReloaded: { (
            uniffiHandle: UInt64,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeEventHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onConfigReloaded(
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterTypeEventHandler.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface EventHandler: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitEventHandler() {
    uniffi_lokii_core_fn_init_callback_vtable_eventhandler(UniffiCallbackInterfaceEventHandler.vtable)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEventHandler: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<EventHandler>()

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = EventHandler

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> EventHandler {
        return EventHandlerImpl(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: EventHandler) -> UnsafeMutableRawPointer {
        guard let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: handleMap.insert(obj: value))) else {
            fatalError("Cast to UnsafeMutableRawPointer failed")
        }
        return ptr
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EventHandler {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: EventHandler, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEventHandler_lift(_ pointer: UnsafeMutableRawPointer) throws -> EventHandler {
    return try FfiConverterTypeEventHandler.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEventHandler_lower(_ value: EventHandler) -> UnsafeMutableRawPointer {
    return FfiConverterTypeEventHandler.lower(value)
}






/**
 * Main entry point for the Lokii Rust core, exposed to Swift via UniFFI.
 */
public protocol LokiiCoreProtocol: AnyObject, Sendable {
    
    /**
     * Check if macOS Full Disk Access is granted.
     */
    func checkFda()  -> Bool
    
    /**
     * Get the current configuration as a JSON string.
     */
    func getConfigJson()  -> String
    
    /**
     * Get watcher diagnostic metrics as a JSON string.
     */
    func getMetrics()  -> String
    
    /**
     * Get current index statistics.
     */
    func getStats()  -> FfiIndexStats
    
    /**
     * Initialize the file index (hot start from cache or cold start via scan).
     * Calls event_handler callbacks for progress and completion.
     * This is blocking — call from a background thread on the Swift side.
     */
    func initialize(eventHandler: EventHandler)  -> FfiStartupMode
    
    /**
     * Check if a background scan (verify) is currently running.
     */
    func isScanning()  -> Bool
    
    /**
     * Open a file with the default application (macOS `open` command).
     */
    func openFile(path: String)  -> Bool
    
    /**
     * Rebuild the index from scratch. Blocking — call from background thread.
     * Caller should check `is_scanning()` first; if true, skip the rebuild.
     */
    func rebuildIndex(eventHandler: EventHandler)  -> Bool
    
    /**
     * Reveal a file in Finder (select it in its parent directory).
     */
    func revealInFinder(path: String)  -> Bool
    
    /**
     * Search the index.
     */
    func search(query: String, mode: FfiSearchMode)  -> FfiSearchResponse
    
    /**
     * Start the config file watcher for hot-reload.
     */
    func startConfigWatcher(eventHandler: EventHandler) 
    
    /**
     * Start the file system watcher. Calls event_handler.on_index_updated
     * whenever the index changes. Non-blocking (spawns a thread internally).
     */
    func startWatcher(eventHandler: EventHandler) 
    
    /**
     * Update configuration from a JSON string. Returns true on success.
     * Writes to TOML file first, then syncs in-memory ConfigStore.
     */
    func updateConfigFromJson(json: String)  -> Bool
    
}
/**
 * Main entry point for the Lokii Rust core, exposed to Swift via UniFFI.
 */
open class LokiiCore: LokiiCoreProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_lokii_core_fn_clone_lokiicore(self.pointer, $0) }
    }
    /**
     * Create a new LokiiCore instance. Loads config from disk.
     */
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_lokii_core_fn_constructor_lokiicore_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_lokii_core_fn_free_lokiicore(pointer, $0) }
    }

    

    
    /**
     * Check if macOS Full Disk Access is granted.
     */
open func checkFda() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_lokii_core_fn_method_lokiicore_check_fda(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get the current configuration as a JSON string.
     */
open func getConfigJson() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_lokii_core_fn_method_lokiicore_get_config_json(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get watcher diagnostic metrics as a JSON string.
     */
open func getMetrics() -> String  {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_lokii_core_fn_method_lokiicore_get_metrics(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Get current index statistics.
     */
open func getStats() -> FfiIndexStats  {
    return try!  FfiConverterTypeFfiIndexStats_lift(try! rustCall() {
    uniffi_lokii_core_fn_method_lokiicore_get_stats(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Initialize the file index (hot start from cache or cold start via scan).
     * Calls event_handler callbacks for progress and completion.
     * This is blocking — call from a background thread on the Swift side.
     */
open func initialize(eventHandler: EventHandler) -> FfiStartupMode  {
    return try!  FfiConverterTypeFfiStartupMode_lift(try! rustCall() {
    uniffi_lokii_core_fn_method_lokiicore_initialize(self.uniffiClonePointer(),
        FfiConverterTypeEventHandler_lower(eventHandler),$0
    )
})
}
    
    /**
     * Check if a background scan (verify) is currently running.
     */
open func isScanning() -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_lokii_core_fn_method_lokiicore_is_scanning(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Open a file with the default application (macOS `open` command).
     */
open func openFile(path: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_lokii_core_fn_method_lokiicore_open_file(self.uniffiClonePointer(),
        FfiConverterString.lower(path),$0
    )
})
}
    
    /**
     * Rebuild the index from scratch. Blocking — call from background thread.
     * Caller should check `is_scanning()` first; if true, skip the rebuild.
     */
open func rebuildIndex(eventHandler: EventHandler) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_lokii_core_fn_method_lokiicore_rebuild_index(self.uniffiClonePointer(),
        FfiConverterTypeEventHandler_lower(eventHandler),$0
    )
})
}
    
    /**
     * Reveal a file in Finder (select it in its parent directory).
     */
open func revealInFinder(path: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_lokii_core_fn_method_lokiicore_reveal_in_finder(self.uniffiClonePointer(),
        FfiConverterString.lower(path),$0
    )
})
}
    
    /**
     * Search the index.
     */
open func search(query: String, mode: FfiSearchMode) -> FfiSearchResponse  {
    return try!  FfiConverterTypeFfiSearchResponse_lift(try! rustCall() {
    uniffi_lokii_core_fn_method_lokiicore_search(self.uniffiClonePointer(),
        FfiConverterString.lower(query),
        FfiConverterTypeFfiSearchMode_lower(mode),$0
    )
})
}
    
    /**
     * Start the config file watcher for hot-reload.
     */
open func startConfigWatcher(eventHandler: EventHandler)  {try! rustCall() {
    uniffi_lokii_core_fn_method_lokiicore_start_config_watcher(self.uniffiClonePointer(),
        FfiConverterTypeEventHandler_lower(eventHandler),$0
    )
}
}
    
    /**
     * Start the file system watcher. Calls event_handler.on_index_updated
     * whenever the index changes. Non-blocking (spawns a thread internally).
     */
open func startWatcher(eventHandler: EventHandler)  {try! rustCall() {
    uniffi_lokii_core_fn_method_lokiicore_start_watcher(self.uniffiClonePointer(),
        FfiConverterTypeEventHandler_lower(eventHandler),$0
    )
}
}
    
    /**
     * Update configuration from a JSON string. Returns true on success.
     * Writes to TOML file first, then syncs in-memory ConfigStore.
     */
open func updateConfigFromJson(json: String) -> Bool  {
    return try!  FfiConverterBool.lift(try! rustCall() {
    uniffi_lokii_core_fn_method_lokiicore_update_config_from_json(self.uniffiClonePointer(),
        FfiConverterString.lower(json),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLokiiCore: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = LokiiCore

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> LokiiCore {
        return LokiiCore(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: LokiiCore) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LokiiCore {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: LokiiCore, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLokiiCore_lift(_ pointer: UnsafeMutableRawPointer) throws -> LokiiCore {
    return try FfiConverterTypeLokiiCore.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLokiiCore_lower(_ value: LokiiCore) -> UnsafeMutableRawPointer {
    return FfiConverterTypeLokiiCore.lower(value)
}




/**
 * Index statistics exposed to Swift.
 */
public struct FfiIndexStats {
    public var totalCount: UInt64
    public var isReady: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(totalCount: UInt64, isReady: Bool) {
        self.totalCount = totalCount
        self.isReady = isReady
    }
}

#if compiler(>=6)
extension FfiIndexStats: Sendable {}
#endif


extension FfiIndexStats: Equatable, Hashable {
    public static func ==(lhs: FfiIndexStats, rhs: FfiIndexStats) -> Bool {
        if lhs.totalCount != rhs.totalCount {
            return false
        }
        if lhs.isReady != rhs.isReady {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(totalCount)
        hasher.combine(isReady)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiIndexStats: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiIndexStats {
        return
            try FfiIndexStats(
                totalCount: FfiConverterUInt64.read(from: &buf), 
                isReady: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: FfiIndexStats, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.totalCount, into: &buf)
        FfiConverterBool.write(value.isReady, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiIndexStats_lift(_ buf: RustBuffer) throws -> FfiIndexStats {
    return try FfiConverterTypeFfiIndexStats.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiIndexStats_lower(_ value: FfiIndexStats) -> RustBuffer {
    return FfiConverterTypeFfiIndexStats.lower(value)
}


/**
 * A byte range for match highlighting.
 */
public struct FfiMatchRange {
    public var start: UInt32
    public var end: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(start: UInt32, end: UInt32) {
        self.start = start
        self.end = end
    }
}

#if compiler(>=6)
extension FfiMatchRange: Sendable {}
#endif


extension FfiMatchRange: Equatable, Hashable {
    public static func ==(lhs: FfiMatchRange, rhs: FfiMatchRange) -> Bool {
        if lhs.start != rhs.start {
            return false
        }
        if lhs.end != rhs.end {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(start)
        hasher.combine(end)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiMatchRange: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiMatchRange {
        return
            try FfiMatchRange(
                start: FfiConverterUInt32.read(from: &buf), 
                end: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: FfiMatchRange, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.start, into: &buf)
        FfiConverterUInt32.write(value.end, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMatchRange_lift(_ buf: RustBuffer) throws -> FfiMatchRange {
    return try FfiConverterTypeFfiMatchRange.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiMatchRange_lower(_ value: FfiMatchRange) -> RustBuffer {
    return FfiConverterTypeFfiMatchRange.lower(value)
}


/**
 * Search response including optional error string.
 */
public struct FfiSearchResponse {
    public var results: [FfiSearchResult]
    public var error: String?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(results: [FfiSearchResult], error: String?) {
        self.results = results
        self.error = error
    }
}

#if compiler(>=6)
extension FfiSearchResponse: Sendable {}
#endif


extension FfiSearchResponse: Equatable, Hashable {
    public static func ==(lhs: FfiSearchResponse, rhs: FfiSearchResponse) -> Bool {
        if lhs.results != rhs.results {
            return false
        }
        if lhs.error != rhs.error {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(results)
        hasher.combine(error)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSearchResponse: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSearchResponse {
        return
            try FfiSearchResponse(
                results: FfiConverterSequenceTypeFfiSearchResult.read(from: &buf), 
                error: FfiConverterOptionString.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSearchResponse, into buf: inout [UInt8]) {
        FfiConverterSequenceTypeFfiSearchResult.write(value.results, into: &buf)
        FfiConverterOptionString.write(value.error, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSearchResponse_lift(_ buf: RustBuffer) throws -> FfiSearchResponse {
    return try FfiConverterTypeFfiSearchResponse.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSearchResponse_lower(_ value: FfiSearchResponse) -> RustBuffer {
    return FfiConverterTypeFfiSearchResponse.lower(value)
}


/**
 * Search result exposed to Swift via UniFFI.
 */
public struct FfiSearchResult {
    public var name: String
    public var path: String
    public var isDir: Bool
    public var size: UInt64
    public var modified: UInt64
    public var created: UInt64
    public var `extension`: String
    public var score: Double
    public var matchPositions: [FfiMatchRange]
    public var searchMode: FfiSearchMode

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, path: String, isDir: Bool, size: UInt64, modified: UInt64, created: UInt64, `extension`: String, score: Double, matchPositions: [FfiMatchRange], searchMode: FfiSearchMode) {
        self.name = name
        self.path = path
        self.isDir = isDir
        self.size = size
        self.modified = modified
        self.created = created
        self.`extension` = `extension`
        self.score = score
        self.matchPositions = matchPositions
        self.searchMode = searchMode
    }
}

#if compiler(>=6)
extension FfiSearchResult: Sendable {}
#endif


extension FfiSearchResult: Equatable, Hashable {
    public static func ==(lhs: FfiSearchResult, rhs: FfiSearchResult) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.path != rhs.path {
            return false
        }
        if lhs.isDir != rhs.isDir {
            return false
        }
        if lhs.size != rhs.size {
            return false
        }
        if lhs.modified != rhs.modified {
            return false
        }
        if lhs.created != rhs.created {
            return false
        }
        if lhs.`extension` != rhs.`extension` {
            return false
        }
        if lhs.score != rhs.score {
            return false
        }
        if lhs.matchPositions != rhs.matchPositions {
            return false
        }
        if lhs.searchMode != rhs.searchMode {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(path)
        hasher.combine(isDir)
        hasher.combine(size)
        hasher.combine(modified)
        hasher.combine(created)
        hasher.combine(`extension`)
        hasher.combine(score)
        hasher.combine(matchPositions)
        hasher.combine(searchMode)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSearchResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSearchResult {
        return
            try FfiSearchResult(
                name: FfiConverterString.read(from: &buf), 
                path: FfiConverterString.read(from: &buf), 
                isDir: FfiConverterBool.read(from: &buf), 
                size: FfiConverterUInt64.read(from: &buf), 
                modified: FfiConverterUInt64.read(from: &buf), 
                created: FfiConverterUInt64.read(from: &buf), 
                extension: FfiConverterString.read(from: &buf), 
                score: FfiConverterDouble.read(from: &buf), 
                matchPositions: FfiConverterSequenceTypeFfiMatchRange.read(from: &buf), 
                searchMode: FfiConverterTypeFfiSearchMode.read(from: &buf)
        )
    }

    public static func write(_ value: FfiSearchResult, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterBool.write(value.isDir, into: &buf)
        FfiConverterUInt64.write(value.size, into: &buf)
        FfiConverterUInt64.write(value.modified, into: &buf)
        FfiConverterUInt64.write(value.created, into: &buf)
        FfiConverterString.write(value.`extension`, into: &buf)
        FfiConverterDouble.write(value.score, into: &buf)
        FfiConverterSequenceTypeFfiMatchRange.write(value.matchPositions, into: &buf)
        FfiConverterTypeFfiSearchMode.write(value.searchMode, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSearchResult_lift(_ buf: RustBuffer) throws -> FfiSearchResult {
    return try FfiConverterTypeFfiSearchResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSearchResult_lower(_ value: FfiSearchResult) -> RustBuffer {
    return FfiConverterTypeFfiSearchResult.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiSearchMode {
    
    case auto
    case substring
    case wildcard
    case regex
    case fuzzy
}


#if compiler(>=6)
extension FfiSearchMode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiSearchMode: FfiConverterRustBuffer {
    typealias SwiftType = FfiSearchMode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiSearchMode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .auto
        
        case 2: return .substring
        
        case 3: return .wildcard
        
        case 4: return .regex
        
        case 5: return .fuzzy
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiSearchMode, into buf: inout [UInt8]) {
        switch value {
        
        
        case .auto:
            writeInt(&buf, Int32(1))
        
        
        case .substring:
            writeInt(&buf, Int32(2))
        
        
        case .wildcard:
            writeInt(&buf, Int32(3))
        
        
        case .regex:
            writeInt(&buf, Int32(4))
        
        
        case .fuzzy:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSearchMode_lift(_ buf: RustBuffer) throws -> FfiSearchMode {
    return try FfiConverterTypeFfiSearchMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiSearchMode_lower(_ value: FfiSearchMode) -> RustBuffer {
    return FfiConverterTypeFfiSearchMode.lower(value)
}


extension FfiSearchMode: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum FfiStartupMode {
    
    case hotStart(cachedCount: UInt64
    )
    case coldStart(scannedCount: UInt64
    )
}


#if compiler(>=6)
extension FfiStartupMode: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiStartupMode: FfiConverterRustBuffer {
    typealias SwiftType = FfiStartupMode

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiStartupMode {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .hotStart(cachedCount: try FfiConverterUInt64.read(from: &buf)
        )
        
        case 2: return .coldStart(scannedCount: try FfiConverterUInt64.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiStartupMode, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .hotStart(cachedCount):
            writeInt(&buf, Int32(1))
            FfiConverterUInt64.write(cachedCount, into: &buf)
            
        
        case let .coldStart(scannedCount):
            writeInt(&buf, Int32(2))
            FfiConverterUInt64.write(scannedCount, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiStartupMode_lift(_ buf: RustBuffer) throws -> FfiStartupMode {
    return try FfiConverterTypeFfiStartupMode.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeFfiStartupMode_lower(_ value: FfiStartupMode) -> RustBuffer {
    return FfiConverterTypeFfiStartupMode.lower(value)
}


extension FfiStartupMode: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiMatchRange: FfiConverterRustBuffer {
    typealias SwiftType = [FfiMatchRange]

    public static func write(_ value: [FfiMatchRange], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiMatchRange.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiMatchRange] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiMatchRange]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiMatchRange.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeFfiSearchResult: FfiConverterRustBuffer {
    typealias SwiftType = [FfiSearchResult]

    public static func write(_ value: [FfiSearchResult], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeFfiSearchResult.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [FfiSearchResult] {
        let len: Int32 = try readInt(&buf)
        var seq = [FfiSearchResult]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeFfiSearchResult.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_lokii_core_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_lokii_core_checksum_method_eventhandler_on_index_progress() != 43913) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_eventhandler_on_index_ready() != 8384) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_eventhandler_on_index_updated() != 41254) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_eventhandler_on_watcher_error() != 16582) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_eventhandler_on_config_reloaded() != 39587) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_lokiicore_check_fda() != 35374) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_lokiicore_get_config_json() != 54941) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_lokiicore_get_metrics() != 746) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_lokiicore_get_stats() != 19023) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_lokiicore_initialize() != 40909) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_lokiicore_is_scanning() != 11801) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_lokiicore_open_file() != 16752) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_lokiicore_rebuild_index() != 27709) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_lokiicore_reveal_in_finder() != 23865) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_lokiicore_search() != 25414) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_lokiicore_start_config_watcher() != 32031) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_lokiicore_start_watcher() != 17814) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_method_lokiicore_update_config_from_json() != 17306) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_lokii_core_checksum_constructor_lokiicore_new() != 44128) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitEventHandler()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureLokiiCoreInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all