// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_HANDLER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_HANDLER_METHOD0
typedef void (*UniffiCallbackInterfaceEventHandlerMethod0)(uint64_t, RustBuffer, uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_HANDLER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_HANDLER_METHOD1
typedef void (*UniffiCallbackInterfaceEventHandlerMethod1)(uint64_t, uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_HANDLER_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_HANDLER_METHOD2
typedef void (*UniffiCallbackInterfaceEventHandlerMethod2)(uint64_t, uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_HANDLER_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_HANDLER_METHOD3
typedef void (*UniffiCallbackInterfaceEventHandlerMethod3)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_HANDLER_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_EVENT_HANDLER_METHOD4
typedef void (*UniffiCallbackInterfaceEventHandlerMethod4)(uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_HANDLER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_EVENT_HANDLER
typedef struct UniffiVTableCallbackInterfaceEventHandler {
    UniffiCallbackInterfaceEventHandlerMethod0 _Nonnull onIndexProgress;
    UniffiCallbackInterfaceEventHandlerMethod1 _Nonnull onIndexReady;
    UniffiCallbackInterfaceEventHandlerMethod2 _Nonnull onIndexUpdated;
    UniffiCallbackInterfaceEventHandlerMethod3 _Nonnull onWatcherError;
    UniffiCallbackInterfaceEventHandlerMethod4 _Nonnull onConfigReloaded;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceEventHandler;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_CLONE_EVENTHANDLER
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_CLONE_EVENTHANDLER
void*_Nonnull uniffi_lokii_core_fn_clone_eventhandler(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_FREE_EVENTHANDLER
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_FREE_EVENTHANDLER
void uniffi_lokii_core_fn_free_eventhandler(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_INIT_CALLBACK_VTABLE_EVENTHANDLER
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_INIT_CALLBACK_VTABLE_EVENTHANDLER
void uniffi_lokii_core_fn_init_callback_vtable_eventhandler(const UniffiVTableCallbackInterfaceEventHandler* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_EVENTHANDLER_ON_INDEX_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_EVENTHANDLER_ON_INDEX_PROGRESS
void uniffi_lokii_core_fn_method_eventhandler_on_index_progress(void*_Nonnull ptr, RustBuffer phase, uint64_t scanned_files, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_EVENTHANDLER_ON_INDEX_READY
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_EVENTHANDLER_ON_INDEX_READY
void uniffi_lokii_core_fn_method_eventhandler_on_index_ready(void*_Nonnull ptr, uint64_t total, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_EVENTHANDLER_ON_INDEX_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_EVENTHANDLER_ON_INDEX_UPDATED
void uniffi_lokii_core_fn_method_eventhandler_on_index_updated(void*_Nonnull ptr, uint64_t new_total, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_EVENTHANDLER_ON_WATCHER_ERROR
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_EVENTHANDLER_ON_WATCHER_ERROR
void uniffi_lokii_core_fn_method_eventhandler_on_watcher_error(void*_Nonnull ptr, RustBuffer msg, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_EVENTHANDLER_ON_CONFIG_RELOADED
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_EVENTHANDLER_ON_CONFIG_RELOADED
void uniffi_lokii_core_fn_method_eventhandler_on_config_reloaded(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_CLONE_LOKIICORE
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_CLONE_LOKIICORE
void*_Nonnull uniffi_lokii_core_fn_clone_lokiicore(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_FREE_LOKIICORE
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_FREE_LOKIICORE
void uniffi_lokii_core_fn_free_lokiicore(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_CONSTRUCTOR_LOKIICORE_NEW
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_CONSTRUCTOR_LOKIICORE_NEW
void*_Nonnull uniffi_lokii_core_fn_constructor_lokiicore_new(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_CHECK_FDA
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_CHECK_FDA
int8_t uniffi_lokii_core_fn_method_lokiicore_check_fda(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_GET_CONFIG_JSON
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_GET_CONFIG_JSON
RustBuffer uniffi_lokii_core_fn_method_lokiicore_get_config_json(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_GET_METRICS
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_GET_METRICS
RustBuffer uniffi_lokii_core_fn_method_lokiicore_get_metrics(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_GET_STATS
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_GET_STATS
RustBuffer uniffi_lokii_core_fn_method_lokiicore_get_stats(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_INITIALIZE
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_INITIALIZE
RustBuffer uniffi_lokii_core_fn_method_lokiicore_initialize(void*_Nonnull ptr, void*_Nonnull event_handler, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_IS_SCANNING
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_IS_SCANNING
int8_t uniffi_lokii_core_fn_method_lokiicore_is_scanning(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_OPEN_FILE
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_OPEN_FILE
int8_t uniffi_lokii_core_fn_method_lokiicore_open_file(void*_Nonnull ptr, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_REBUILD_INDEX
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_REBUILD_INDEX
int8_t uniffi_lokii_core_fn_method_lokiicore_rebuild_index(void*_Nonnull ptr, void*_Nonnull event_handler, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_REVEAL_IN_FINDER
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_REVEAL_IN_FINDER
int8_t uniffi_lokii_core_fn_method_lokiicore_reveal_in_finder(void*_Nonnull ptr, RustBuffer path, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_SEARCH
RustBuffer uniffi_lokii_core_fn_method_lokiicore_search(void*_Nonnull ptr, RustBuffer query, RustBuffer mode, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_START_CONFIG_WATCHER
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_START_CONFIG_WATCHER
void uniffi_lokii_core_fn_method_lokiicore_start_config_watcher(void*_Nonnull ptr, void*_Nonnull event_handler, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_START_WATCHER
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_START_WATCHER
void uniffi_lokii_core_fn_method_lokiicore_start_watcher(void*_Nonnull ptr, void*_Nonnull event_handler, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_UPDATE_CONFIG_FROM_JSON
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_FN_METHOD_LOKIICORE_UPDATE_CONFIG_FROM_JSON
int8_t uniffi_lokii_core_fn_method_lokiicore_update_config_from_json(void*_Nonnull ptr, RustBuffer json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUSTBUFFER_ALLOC
RustBuffer ffi_lokii_core_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_lokii_core_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUSTBUFFER_FREE
void ffi_lokii_core_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUSTBUFFER_RESERVE
RustBuffer ffi_lokii_core_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_U8
void ffi_lokii_core_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_U8
void ffi_lokii_core_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_U8
void ffi_lokii_core_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_lokii_core_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_I8
void ffi_lokii_core_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_I8
void ffi_lokii_core_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_I8
void ffi_lokii_core_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_I8
int8_t ffi_lokii_core_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_U16
void ffi_lokii_core_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_U16
void ffi_lokii_core_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_U16
void ffi_lokii_core_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_lokii_core_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_I16
void ffi_lokii_core_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_I16
void ffi_lokii_core_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_I16
void ffi_lokii_core_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_I16
int16_t ffi_lokii_core_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_U32
void ffi_lokii_core_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_U32
void ffi_lokii_core_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_U32
void ffi_lokii_core_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_lokii_core_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_I32
void ffi_lokii_core_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_I32
void ffi_lokii_core_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_I32
void ffi_lokii_core_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_I32
int32_t ffi_lokii_core_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_U64
void ffi_lokii_core_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_U64
void ffi_lokii_core_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_U64
void ffi_lokii_core_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_lokii_core_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_I64
void ffi_lokii_core_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_I64
void ffi_lokii_core_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_I64
void ffi_lokii_core_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_I64
int64_t ffi_lokii_core_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_F32
void ffi_lokii_core_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_F32
void ffi_lokii_core_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_F32
void ffi_lokii_core_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_F32
float ffi_lokii_core_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_F64
void ffi_lokii_core_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_F64
void ffi_lokii_core_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_F64
void ffi_lokii_core_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_F64
double ffi_lokii_core_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_POINTER
void ffi_lokii_core_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_POINTER
void ffi_lokii_core_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_POINTER
void ffi_lokii_core_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_lokii_core_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_lokii_core_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_lokii_core_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_lokii_core_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_lokii_core_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_POLL_VOID
void ffi_lokii_core_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_CANCEL_VOID
void ffi_lokii_core_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_FREE_VOID
void ffi_lokii_core_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_RUST_FUTURE_COMPLETE_VOID
void ffi_lokii_core_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_EVENTHANDLER_ON_INDEX_PROGRESS
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_EVENTHANDLER_ON_INDEX_PROGRESS
uint16_t uniffi_lokii_core_checksum_method_eventhandler_on_index_progress(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_EVENTHANDLER_ON_INDEX_READY
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_EVENTHANDLER_ON_INDEX_READY
uint16_t uniffi_lokii_core_checksum_method_eventhandler_on_index_ready(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_EVENTHANDLER_ON_INDEX_UPDATED
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_EVENTHANDLER_ON_INDEX_UPDATED
uint16_t uniffi_lokii_core_checksum_method_eventhandler_on_index_updated(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_EVENTHANDLER_ON_WATCHER_ERROR
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_EVENTHANDLER_ON_WATCHER_ERROR
uint16_t uniffi_lokii_core_checksum_method_eventhandler_on_watcher_error(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_EVENTHANDLER_ON_CONFIG_RELOADED
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_EVENTHANDLER_ON_CONFIG_RELOADED
uint16_t uniffi_lokii_core_checksum_method_eventhandler_on_config_reloaded(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_CHECK_FDA
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_CHECK_FDA
uint16_t uniffi_lokii_core_checksum_method_lokiicore_check_fda(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_GET_CONFIG_JSON
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_GET_CONFIG_JSON
uint16_t uniffi_lokii_core_checksum_method_lokiicore_get_config_json(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_GET_METRICS
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_GET_METRICS
uint16_t uniffi_lokii_core_checksum_method_lokiicore_get_metrics(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_GET_STATS
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_GET_STATS
uint16_t uniffi_lokii_core_checksum_method_lokiicore_get_stats(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_INITIALIZE
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_INITIALIZE
uint16_t uniffi_lokii_core_checksum_method_lokiicore_initialize(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_IS_SCANNING
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_IS_SCANNING
uint16_t uniffi_lokii_core_checksum_method_lokiicore_is_scanning(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_OPEN_FILE
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_OPEN_FILE
uint16_t uniffi_lokii_core_checksum_method_lokiicore_open_file(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_REBUILD_INDEX
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_REBUILD_INDEX
uint16_t uniffi_lokii_core_checksum_method_lokiicore_rebuild_index(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_REVEAL_IN_FINDER
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_REVEAL_IN_FINDER
uint16_t uniffi_lokii_core_checksum_method_lokiicore_reveal_in_finder(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_SEARCH
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_SEARCH
uint16_t uniffi_lokii_core_checksum_method_lokiicore_search(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_START_CONFIG_WATCHER
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_START_CONFIG_WATCHER
uint16_t uniffi_lokii_core_checksum_method_lokiicore_start_config_watcher(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_START_WATCHER
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_START_WATCHER
uint16_t uniffi_lokii_core_checksum_method_lokiicore_start_watcher(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_UPDATE_CONFIG_FROM_JSON
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_METHOD_LOKIICORE_UPDATE_CONFIG_FROM_JSON
uint16_t uniffi_lokii_core_checksum_method_lokiicore_update_config_from_json(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_CONSTRUCTOR_LOKIICORE_NEW
#define UNIFFI_FFIDEF_UNIFFI_LOKII_CORE_CHECKSUM_CONSTRUCTOR_LOKIICORE_NEW
uint16_t uniffi_lokii_core_checksum_constructor_lokiicore_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_LOKII_CORE_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_LOKII_CORE_UNIFFI_CONTRACT_VERSION
uint32_t ffi_lokii_core_uniffi_contract_version(void
    
);
#endif

